Fix kernel-vanilla build issue
Fix:

  [  315s]   CC [M]  fs/fat/namei_vfat.o
  [  315s]   CC      kernel/elfcore.o
  [  315s] ../scripts/Makefile.build:302: recipe for target 'kernel/elfcore.o' failed
  [  315s] Cannot find symbol for section 1: .text.
  [  315s] kernel/elfcore.o: failed
  [  315s] make[3]: *** [kernel/elfcore.o] Error 1

due to toolchain updates and the patch missing in the vanilla flavor. So
move it there.

Signed-off-by: Borislav Petkov <bp@suse.de>

suse-commit: 23d6a8f5473e345332daf5b110f3a2880677dcad